# Provide the names of the study area and the name of the reference data, if available, as a human-readable string (max 22 characters).
# This will be used for:
# - plot labelling
# - result labelling
# - exported reports

area_name: 'Denmark' # provide area name here
reference_name: 'GeoDanmark' # provide name of reference dataset

# Provide the name of the study area/project as a slug.
# (Use https://you.tools/slugify/ if unsure)
# This will be used for:
# - folder and subfolder structure setup 
study_area: 'dk' # provide name of study area

# Provide the CRS which will be used throughout the anaylysis. 
# This must be a projected CRS with meters as unit length. 
study_crs: 'EPSG:25832' # The CRS you want to use for the analysis. 

# Choose whether plots should be saved in low or high resolution.
# If 'low', plots are saved as png. If 'high', plots are saved as svg (this will lead to significantly larger files)
plot_resolution: 'low'

# Filepaths with the data and results from running BikeDNA
bikedna_data_filepath: "/Users/anev/Dropbox/ITU/repositories/bikedna_denmark/data/"
results_data_filepath: "/Users/anev/Dropbox/ITU/repositories/bikedna_denmark/results/"


